// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP8U9hwqKVRAzcqW2R4b3-HBeWaF_B9LE',
    appId: '1:701719336486:web:b14be5d539991d5bc038e7',
    messagingSenderId: '701719336486',
    projectId: 'pizzaria-a949a',
    authDomain: 'pizzaria-a949a.firebaseapp.com',
    storageBucket: 'pizzaria-a949a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHZwQBgC5oMfN3jXZhhJK6ONO8gDnGDco',
    appId: '1:701719336486:android:bb780bbcd28d4648c038e7',
    messagingSenderId: '701719336486',
    projectId: 'pizzaria-a949a',
    storageBucket: 'pizzaria-a949a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1lTSpuRbP7YrGGzuYGPqfvFXwwHhNNIE',
    appId: '1:701719336486:ios:9208ce8b04165a50c038e7',
    messagingSenderId: '701719336486',
    projectId: 'pizzaria-a949a',
    storageBucket: 'pizzaria-a949a.appspot.com',
    iosClientId: '701719336486-ro45k68okr7trfhe29dgt26la4ffi7im.apps.googleusercontent.com',
    iosBundleId: 'by.kapold.pizzaPlaceApp',
  );
}
